### ISSUE TITLE
Logs shouldn't say "Using linked mysql container" when using an external mysql database

### ISSUE THREAD

**Issue by joeldeteves** [CampbellSoftwareSolutions/docker-osticket#39]
A minor issue but enough to lead someone who's troubleshooting astray. The docker logs shouldn't say "Using linked mysql container" when connected to an external mysql database (vs mysql running in a container).

**Comment by martin-css** [comment]
I suspect this happened because you supplied an environmental variable `MYSQL_PORT` when creating the container? The presence of this variable is what the code used to detect if it was a linked container or not.

This has been changed to check `MYSQL_ENV_MYSQL_PASSWORD` instead which should hopefully prevent this occurring again if that was the reason.

**Comment by joeldeteves** [comment]
Yes we did supply the variable, but we pointed it to a non-containerized MySQL instance (so it's a bit misleading for it to say 'linked container'. But it's not a big deal, it's more visual than anything :-)

Thanks for the great container! I learned a lot about supervisord, nginx and alpine from using it.
