### ISSUE TITLE
Update to v1.12.2

### ISSUE THREAD

**Issue by kosli** [CampbellSoftwareSolutions/docker-osticket#67]
Please update the docker image to version 1.12.2 (https://github.com/osTicket/osTicket/releases) Thanks.

**Comment by aholthus-cl** [comment]
Pretty please update the docker image to version 1.12.2 (https://github.com/osTicket/osTicket/releases) Thanks.

**Comment by lubo** [comment]
This issue is one of the reasons why we @devinsolutions have created [our own fork](https://github.com/devinsolutions/docker-osticket). I don't know if you have checked out [Network graph](https://github.com/CampbellSoftwareSolutions/docker-osticket/network), but we did it a while ago and we've been keeping it up-to-date constantly. We run that image in production, so prompt security updates go without saying. We'll be happy if you find it useful.

**Comment by robinjos333** [comment]
Waiting for the update. Please update...
